//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int id { get; set; }
        public string status { get; set; }
        public int total_quantity { get; set; }
        public int restaurant_id { get; set; }
        public int employee_id { get; set; }
        public int admin_id { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual employee employee { get; set; }
        public virtual food food { get; set; }
        public virtual restaurant restaurant { get; set; }
    }
}
